apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: init-ns-kubearchiveconfig
spec:
  rules:
  - name: init-ns-kubearchiveconfig
    match:
      any:
      - resources:
          kinds:
          - Namespace
          operations:
          - CREATE
          selector:
            matchExpressions:
            - key: konflux-ci.dev/tenant
              operator: Exists
    generate:
      apiVersion: kubearchive.kubearchive.org/v1alpha1
      kind: KubeArchiveConfig
      name: konflux-tenant
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          resources:
            - selector:
                apiVersion: tekton.dev/v1
                kind: PipelineRun
              archiveOnDelete: "true"
            - selector:
                apiVersion: tekton.dev/v1
                kind: TaskRun
              archiveOnDelete: "true"
            - selector:
                apiVersion: v1
                kind: Pod
              archiveOnDelete: "true"
            - selector:
                apiVersion: appstudio.redhat.com/v1alpha1
                kind: Snapshot
              archiveOnDelete: "true"
            - selector:
                apiVersion: appstudio.redhat.com/v1alpha1
                kind: Release
              archiveOnDelete: "true"
