---
apiVersion: v1
kind: Pod
metadata:
  name: enterprise-pod
  labels:
    tekton.dev/task: verify-enterprise-contract
spec:
  containers:
  - image: bash
    name: enterprise-pod
    resources:
      requests:
        cpu: "1m"
        memory: "1Mi"
