apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tekton-pr-taskrun-set-imagepullpolicy-build-binding.yaml
- tekton-pr-taskrun-set-imagepullpolicy-enterprise-binding.yaml
- tekton-pr-taskrun-set-imagepullpolicy.yaml
