apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: single-namespace-viewer
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
- apiGroups:
  - "v1"
  resources:
  - namespaces
  verbs: ["get", "watch"]

