---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: tekton-pr-taskrun-reduce-resource-build.konflux-ci.dev
spec:
  matchResources:
    objectSelector:
      matchLabels:
        pipelines.appstudio.openshift.io/type: build
  policyName: tekton-pr-taskrun-reduce-resource.konflux-ci.dev
